baseurl = "https://compassionate-beaver-d37437.netlify.com/"
title = "jkseolab"
languageCode = "ko-KR"
 
paginate = 2

disqusShortname = ""
googleAnalytics = ""

[author]
    name = "jkseo"
    email = "forgtogto@gmail.com"
