baseurl = "jkseolab"
title = "jkseolab"
languageCode = "ko-KR"

theme = "hugo-hello-programmer" 

paginate = 2

disqusShortname = ""
googleAnalytics = ""

[author]
    name = "jkseo"
    email = "forgtogto@gmail.com"
