baseurl = "https://jkseolab.netlify.com"
title = "jkseolab"
languageCode = "ko-KR"

paginate = 8

disqusShortname = "jeongkwonseo"
googleAnalytics = "UA-136123061-1"

[author]
    name = "jkseo"
    email = "forgtogto@gmail.com"
